services:
  - type: web
    name: app-financas-web
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn financeiro.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: WEB_CONCURRENCY
        value: "4"
