# Generated by Django 4.2 on 2026-04-22 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='RendaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendas_extras', to='perfis.perfil')),
            ],
            options={
                'ordering': ('-data', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='SalarioParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_recebimento', models.PositiveSmallIntegerField(choices=[(5, 'Dia 5'), (20, 'Dia 20'), (30, 'Dia 30')])),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_salariais', to='perfis.perfil')),
            ],
            options={
                'ordering': ('dia_recebimento',),
                'unique_together': {('perfil', 'dia_recebimento')},
            },
        ),
    ]
