# Generated by Django 4.2 on 2026-04-22 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor', models.CharField(default='#ff9f43', max_length=20)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_parcelas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)])),
                ('dia_vencimento', models.PositiveSmallIntegerField(choices=[(5, 'Dia 5'), (20, 'Dia 20'), (30, 'Dia 30')])),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado')], default='ativo', max_length=10)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='perfis.perfil')),
            ],
            options={
                'ordering': ('status', 'dia_vencimento', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='gastos.gasto')),
            ],
            options={
                'ordering': ('numero',),
                'unique_together': {('gasto', 'numero')},
            },
        ),
    ]
