# Generated by Django 4.2 on 2026-04-23 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
        ("perfis", "0004_perfil_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoDebito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos_debito",
                        to="perfis.perfil",
                    ),
                ),
            ],
            options={
                "ordering": ("-data", "-criado_em"),
            },
        ),
    ]
